// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPush() {
  return window['go']['main']['App']['CancelPush']();
}

export function DeleteRepo(arg1) {
  return window['go']['main']['App']['DeleteRepo'](arg1);
}

export function GetGitHubProfile() {
  return window['go']['main']['App']['GetGitHubProfile']();
}

export function GetLastPushedRepo() {
  return window['go']['main']['App']['GetLastPushedRepo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchRepos(arg1) {
  return window['go']['main']['App']['SearchRepos'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartPush(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['StartPush'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
