// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';
import {history} from '../models';
import {config} from '../models';

export function CancelPush():Promise<void>;

export function DeleteRepo(arg1:string):Promise<void>;

export function GetGitHubProfile():Promise<github.GitHubProfile>;

export function GetLastPushedRepo():Promise<history.PushedRepo>;

export function GetSettings():Promise<config.AppConfig>;

export function OpenBrowser(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.AppConfig):Promise<void>;

export function SearchRepos(arg1:string):Promise<Array<github.RepositoryInfo>>;

export function SelectDirectory():Promise<string>;

export function StartPush(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:string):Promise<void>;
